apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: 989988/demoapp:2.0.0
        imagePullPolicy: Always 
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/ok
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/ok
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
